completed es6-modules exercise - Nick Sturz
nsturz/rc0622-code-solutions pull request #78
Opened 2022-08-30 22:39 UTC by nsturz

https://user-images.githubusercontent.com/94485412/187555892-7610d9c5-7f88-407f-b7e5-f58fb8fa94b6.mov

2022-08-30 22:50 UTC, scbowler requested changes
A few updates needed. Make sure you are testing by running the `npm run build` command. Let me know if you have any questions.

2022-08-30 22:50 UTC, scbowler commented on es6-modules/src/components/todo-app.js
> +export class TodoApp {
This should be `export default`

2022-08-30 22:50 UTC, scbowler commented on es6-modules/src/components/todo-form.js
> +export class TodoForm {
This should be `export default`

2022-08-30 22:50 UTC, scbowler commented on es6-modules/src/components/todo-form.js
> +import createElement from '../lib';
`createElement` should be a "named export" so it should use curly brackets for the import.
```JAVASCRIPT
import { createElement } from '../lib';
```

2022-08-30 22:50 UTC, scbowler commented on es6-modules/src/components/todo-list.js
> +import createElement from '../lib';
`createElement` should be a "named export" so it should use curly brackets for the import.
```JAVASCRIPT
import { createElement } from '../lib';
```

2022-08-30 22:50 UTC, scbowler commented on es6-modules/src/components/todo-list.js
> +export class TodoList {
This should be `export default`

2022-08-30 22:50 UTC, scbowler commented on es6-modules/src/lib/create-element.js
> +import toArray from '.to-array';
Missing a slash in the file path.
```JAVASCRIPT
import toArray from './to-array';
```

2022-08-30 22:50 UTC, scbowler commented on es6-modules/src/lib/create-element.js
> +export function createElement(tagName, attributes, children = []) {
This should be `export default`

2022-08-30 22:50 UTC, scbowler commented on es6-modules/src/lib/noop.js
> +export function noop() {}
Should be `export default`

2022-08-30 22:50 UTC, scbowler commented on es6-modules/src/lib/to-array.js
> +export function toArray(value) {
Should be `export default`

2022-08-30 23:06 UTC, nsturz commented
addressed all change requests

2022-08-31 00:32 UTC, scbowler approved these changes
Good job implementing the feedback, looks great!

2022-08-31 18:08 UTC, merged